/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import classes.exam;
import classes.student;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MSI Gaming
 */
public class formexam extends javax.swing.JInternalFrame {

  
    public formexam() {
        initComponents();
        select();
    }
    private PreparedStatement ps;
    private ResultSet r;
    private String sql;
    private exam ex = new exam();
    private DefaultTableModel mod = new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtexamid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboexamtypeid = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("ExamtypeID:");

        txtexamid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("ExamID:");

        comboexamtypeid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboexamtypeidMouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Name:");

        txtname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Start Date:");

        btnsave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnclose.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ExamID", "ExamtypeID", "Name", "Start date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel15.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel15.setText("Exam's   Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(90, 90, 90)
                            .addComponent(txtexamid, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboexamtypeid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtexamid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboexamtypeid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btnedit)
                            .addComponent(btnclear)
                            .addComponent(btnclose))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public TableModel select(){
        try {
            sql="SELECT * FROM tbexam";
            ps=connectionDB.getConnection().prepareStatement(sql);
            r=ps.executeQuery();
            while(r.next()){
                String examid = r.getString(1);
                String examtypeid=r.getString(2);
                String name=r.getString(3);
                String date=r.getString(4);
                
                String []row = {examid, examtypeid,name, date};
                
                mod=(DefaultTableModel)table.getModel();
                mod.addRow(row);
                
            }
            return mod;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    private void clear(){
            txtexamid.setText("AUTO ID");
            txtname.setText(""); 
            txtdate.setDate(new java.util.Date());  
            comboexamtypeid.setSelectedIndex(0);
            mod.setRowCount(0);
            select();
        }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       try {
            
            r=ex.selectexamtype();
            while(r.next()){
                String examtypeid=r.getString("examtype");
                comboexamtypeid.addItem(examtypeid);
                
                
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       String name = txtname.getText();
   
      
       String examtypeid= comboexamtypeid.getSelectedItem()+"";
       String []rt=examtypeid.split(" - ");
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String startdate = sdf.format(txtdate.getDate());
       
       ex = new exam(0, rt[0], name, startdate);
       
       if(ex.insert()){
           
           JOptionPane.showMessageDialog(this, "exam Save success..........!");
           clear();
       }else{
           JOptionPane.showMessageDialog(this, "Save fail..............!");
       }    
// TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void comboexamtypeidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboexamtypeidMouseEntered
       String g = comboexamtypeid.getSelectedItem().toString()+"";
        String []examtype = g.split(" - ");
        try {
            sql="SELECT name FROM tbexam_type WHERE exam_type_id="+examtype[0]+"";
            ps=connectionDB.getConnection().prepareStatement(sql);
            r=ps.executeQuery();
            while(r.next()){
                String nametype = r.getString("name");
                txtname.setText(nametype);
                txtname.setText(nametype);
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }  
    }//GEN-LAST:event_comboexamtypeidMouseEntered

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
            int row =table.getSelectedRow();
        //String []row = {examid, examtypeid, date};
             txtexamid.setText(table.getValueAt(row, 0)+"");
             txtname.setText(table.getValueAt(row, 2)+"");
             
             
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           
            try {
               
             java.util.Date Date = sdf.parse(table.getValueAt(row,3 ).toString());
             txtdate.setDate(Date);
             
             
            sql="SELECT CONCAT(R.exam_type_id,' - ',RT.name) AS lname FROM tbexam AS R INNER JOIN tbexam_type AS RT ON R.exam_type_id=RT.exam_type_id "
                    + "WHERE exam_id="+txtexamid.getText()+"";
//            
        ps = connectionDB.getConnection().prepareStatement(sql);
        r = ps.executeQuery();
        while(r.next()){
            String examtypeid = r.getString("lname");
            comboexamtypeid.setSelectedItem(examtypeid);
        }
        ps.close();
        r.close();
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        String name = txtname.getText();
        int id = Integer.parseInt(txtexamid.getText());
       String examtypeid= comboexamtypeid.getSelectedItem()+"";
       String []rt=examtypeid.split(" - ");
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String startdate = sdf.format(txtdate.getDate());
       
       ex = new exam(id, rt[0], name, startdate);
       
       if(ex.update()){
           
           JOptionPane.showMessageDialog(this, "exam update success..........!");
           clear();
       }else{
           JOptionPane.showMessageDialog(this, "update fail..............!");
       }   
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> comboexamtypeid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtexamid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
